
version: '3.6'
services:

  influxdb:
    image: influxdb:2.7.10
    container_name: influxdb
    
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana-server
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admins
      - GF_INSTALL_PLUGINS=marcuscalidus-svg-panel
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1ms
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafanaVolume
     
  
volumes:
  grafana_data: {}
  influxdb_data: {}

